src/wp/Device.cs
ANID is only supported up to Windows Phone 7.5
=> Support for Windows Phone 8 ANID2

README.md, src/android/Device.java, src/ios/CDVDevice.m, src/wp/Device.cs, tests/tests.js, www/device.js
added isVirtual boolean property
=> CB 9847 Cannot tell when running on Simulator

src/ios/CDVDevice.m
https://issues.apache.org/jira/browse/CB-9865
=> CB-9865 Better simulator detection for iOS

README.md, src/android/Device.java, tests/tests.js, www/device.js
Added basic support for hardware serial number for Android platform
=> Added basic Android support for hardware serial number

tests/tests.js
https://issues.apache.org/jira/browse/CB-9847
=> CB-9847 Fixed merge error of 408c3a20be976ca5b814c9f161c31d4edf1c00fc

README.md
See the [CB-9923](https://issues.apache.org/jira/browse/CB-9923) and #25 for details
=> CB-9923 Update `device.platform` documentation for browser platform

README.md
The property manufacturer was missing in the documentation.
=> Property manufacturer documented

src/ios/CDVDevice.m
Hi, just a quick cleanup of dictionary creation on iOS.
No functional changes, but I like to write those dictionaries like this these days. For readability mostly.
Cheers,
Eddy
=> Refactored deviceInfo on iOS for better readability

package.json
=> CB-13702: Fix to allow 2.0.0 version install

.travis.yml
=> CB-13752: Add build-tools-26.0.2 to travis

.travis.yml
This PR brings this plugin's Travis CI configuration in line with the new configuration file of paramedic https://github.com/apache/cordova-paramedic/blob/master/.travis.yml which was written in a way that allows simple distribution to all plugins.
=> Update Travis CI configuration for new paramedic

package.json
=> chore: replaces bugs URL

package-lock.json, package.json, plugin.xml, tests/package.json, tests/plugin.xml
n/a
Prepare for minor changes
bump to `2.1.0-dev`
n/a
=> chore: bump plugin to 2.1.0-dev

README.md
n/a
closes #100
Updated README
n/a
=> doc(README): update device.cordova info

README.md
ios
closes #147
Updated documentation to explain the iOS quirks.
n/a
=> doc(ios): add device.model quirks

package-lock.json
n/a
Uses the latest package-lock version 2
Also will resolve the recent PRs
Closes #160
Closes #161
Closes #162
Closes #163
Closes #164
Closes #165
Rebuilt the package-lock with v2
n/a
=> chore: rebuild package-lock v2

package.json, plugin.xml, tests/package.json, tests/plugin.xml
n/a
prepare for 2.2.0 release
bump package to 2.2.0-dev
n/a
=> chore: prepare package for 2.2.0-dev

package.json, plugin.xml, tests/package.json, tests/plugin.xml
n/a
Bump for 3.0.0 release
Bump package version
n/a
=> chore: bump version 3.0.0-dev

package-lock.json
n/a
add missing changes to package-lock
used npm to update package-lock.json changes to match against package.json
n/a
=> chore: bump version 3.0.0-dev - package-lock

package-lock.json
n/a
- Rebuilt package-lock.json with v3.
- Resolves audit for dev
n/a
=> chore: rebuilt package-lock.json w/ version 3

.github/workflows/ios.yml
N/A
Sync GitHub Action workflow with Paramedic
Update ios.yml. Others are already updated.
N/A
=> ci: sync workflow w/ paramedic
