apache/cordova-plugin-device

- src/browser/DeviceProxy.js
Added support for Internet Explorer and other browsers when using the new "browser" platform in Cordova 4.
Chrome, Safari, and Firefox were already supported, but when using IE or any other browser an error would occur because the user agent string wasn't recognized.
I added specific logic to parse Internet Explorer's user agent string.  Note that IE 11's user agent string doesn't include "MSIE", so I search for "Trident" as well.
I also fixed the bug that was causing an error if the user agent wasn't recognized, so if a browser other than Chrome, Safari, Firefox, or IE is used, the plugin will still work.  It just won't have the `device.model` or `device.version` set.
> Internet Explorer browser support

- src/android/Device.java
- src/blackberry10/index.js
- src/ios/CDVDevice.m
- www/device.js
For some platforms it makes sense to be able to list the Manufacturer for a device. These changes allow retrieval of manufacturer name for Android, iOS & Blackberry. Have not added to other platforms as I have no access to those or know the API's.
> adds new property 'manufacturer' for Android (and hardcoded for iOS, Blackberry)

- README.md
- src/android/Device.java
- src/ios/CDVDevice.m
- www/device.js
@purplecabbage change pr and property name to isSimulator.
> add isSimulator for iOS & Android device

- README.md
- src/windows/DeviceProxy.js
- www/device.js
This adds the `isVirtual` for the Windows 8.x Desktop and Phone platforms.
Virtual means the app is running in the Windows Simulator (a remote session) or the Windows Phone/Mobile Emulator.
I also simplified the retrieval of the device manufacture name by using `Windows.Security.ExchangeActiveSyncProvisioning.EasClientDeviceInformation`
> Feature add is simulator for windows

- src/browser/DeviceProxy.js
Browser
Allows the plugin to properly detect Edge browser.
https://issues.apache.org/jira/browse/CB-12105
Tested on Edge 38, Chrome 56, Firefox 51
> CB-12105 (browser) Properly detect Edge

- .appveyor.yml
Windows
https://issues.apache.org/jira/browse/CB-12935
Enables AppVeyor build
See the build!
> CB-12935: (windows) Enable paramedic builds on AppVeyor

- README.md
- src/browser/DeviceProxy.js
Browser
Introduces device.isVirtual to browser platform and makes it always equal `false`
an automated test run on browser platform
> CB-13113 (browser) device.isVirtual is always false

- plugin.xml
ios
removes libz.tbd as it's not needed
tested on ios 9 and ios 11 devices
> CB-13893: (ios) delete libz.tbd from device plugin

- src/ios/CDVDevice.m
(ios) using correct device.model on simulator
> CB-14106m - device.model is different on simulator and on real device

- www/device.js
All
Presenting an error to a user in an alert box is bad UX. And it's annoying as a developer too.
Plus, I'd like to deprecate `cordova/utils.alert` and this is the only occurrence in a core plugin.
- log error to console instead of using alert
- clarify origin of error message
None
> Log error to console, not to dialog box

- .npmignore
>  chore(npm): improve ignore list 

- .eslintrc.yml
- package-lock.json
- package.json
- src/browser/DeviceProxy.js
- src/windows/DeviceProxy.js
- tests/tests.js
- www/device.js
Ref https://github.com/apache/cordova/issues/142
Ref https://github.com/apache/cordova/issues/4
Depends on #120, therefor WIP
> refactor(eslint): use cordova-eslint 

- .appveyor.yml
This aligns the repo with the other plugins - most of them have x64 and x86 tests.
> ci(appveyor): adds x64 build

- README.md
The behaviour of `device.uuid` has been changed since Android 8.0 https://developer.android.com/about/versions/oreo/android-8.0-changes#privacy-all
None.
I came to know about this change in Android 8.0 a few hours back so thought of updating the same in this plugin as many developers rely on this `device.uuid`.
The documentation about `device.uuid` was outdated and its behaviour was changed in Android 8.0. This only changes the documentation in README.md about `device.uuid` behaviour in Android.
N/A.
> docs: Update information about device.uuid for Android

- README.md
Docs
Closes https://github.com/apache/cordova-plugin-device/issues/111
Added notes on the `serial` property for android and why it now returns `UNKNOWN`.
> doc: Noted android quirks on serial property

- .eslintignore
- .gitignore
- .npmignore
- package.json
- plugin.xml
- src/electron/index.js
- src/electron/package.json
electron
Add Electron Support
closes: #102
closes: #99
Added sub-npm-package for Cordova-Electron
* Build Test
> feat(electron): add support

- plugin.xml
- src/osx/CDVDevice.h
- src/osx/CDVDevice.m
osx
The plugin is not working with the osx platform right now.
This PR changes the name of the class to the same name as the JS classname and this makes this plugin work again.
Added plugin and ran tests on mac
> fix(osx): rename classes to fix plugin

- src/electron/package.json
Electron
Fixes a typo in the `description` filed in the Electron `package.json` file.
`Supprot` => `Support`
n/a
> chore(electron): fix Electron package.json typo

- README.md
- src/android/Device.java
- www/device.js
Android
Resolves #142
Refactored and re-added the getSDKVersion method.
`getInfo` response to contain `sdkVersion` property and added to the `window.device` object.
- Build App
- Confirmed `window.device` object
- Called `getInfo`
```javascript
device.getInfo(
result => {
console.log("Success Result", result);
},
error => {
console.log("Error", error);
}
)
```
> feat(android): getInfo response to include sdkVersion

- README.md
- types/index.d.ts
Android only
Aligning documentation and types! Nothin' special...
As above
Have confirmed the types work locally for me. No other code changes.
> doc(android): clarify documentation and types for sdkVersion field

- package.json
The electron engine requirement is set for version 3.0.0, which doesn’t exist.
I have added a new entry for 2.1.0 as that’s where electron support was added.
> fix(electron): use correct engine for 2.1.0 in package.json

- README.md
The android quirk for android is incorrect, model returns the model name, not the product name.
> docs(android): correct model description

- README.md
- plugin.xml
- src/ios/CDVDevice.bundle/PrivacyInfo.xcprivacy
ios
Support Apple's Privacy Manifest requirements
closes https://github.com/apache/cordova-plugin-device/issues/192
- Created a resource bundle
- Added `PrivacyInfo.xcprivacy` to the resource bundle
- Load bundle into iOS project with `resource-file` in `plugin.xml`
The bundle is prefixed with Cordova's internal `CDV` namespace. 
Note for third-party plugins: When creating a bundle or even class names, it is recommended to establish your own namespace and utilize a unique identifier to prevent conflicts with other plugins.
- platform add
- plugin add
- archive project
- generated privacy report
> feat(ios): add bundled resources for privacy manifest

- src/android/Device.java
There are unused variables, methods and fireos leftovers that are unused
> refactor(android)!: Remove unused code

- plugin.xml
use github links instead of jira and apache git
> chore: Use github links in plugin.xml

- package-lock.json
- package.json
- plugin.xml
android
Added platform engine requirement for `cordova-android` because of recent changes applied by #62 .
Set `cordova-android >= 7.0.0`.
n/a
> fix(android)!: set platform requirement >= 7.0.0

- .github/workflows/android.yml
- .github/workflows/chrome.yml
- .github/workflows/ios.yml
- .github/workflows/lint.yml
n/a
Update CI Workflow
Updated:
- Dependencies
- Android test matrix
- Use linux & enable KVM
- Use node 20
n/a
> ci: update gh-action's workflow
